title: Siddharth Vashishtha
author: Siddharth Vashishtha
url: "https://sidsvash26.github.io"
baseurl: ""

description: Siddharth Vashishtha's website

markdown: kramdown

google_analytics_tracking_id: 

sass:
    style: compressed
    sass_dir: _sass

include: ["_pages"]

github_username:      sidsvash26
linkedin_username:    siddharthvashishtha
quora_username:       Siddharth-Vashishtha
wordpress_username:   siddharthvashishtha
twitter_username:     sidvash
youtube_username: channel/UCXcGG7apJdc6Atd9PvIF64w?